import Head from "next/head";
import Image from "next/image";
import logo from "../images/skalez_logo.png";
import { BsFillMoonStarsFill } from "react-icons/bs";
import {
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub,
} from "react-icons/ai";
import profile from "../images/profile.jpg";
import code from "../images/code.png";
import consulting from "../images/consulting.png";
import design from "../images/design.png";
import projectOne from "../images/project-1.png";
import projectTwo from "../images/project-2.png";
import projectThree from "../images/project-3.png";
import projectFour from "../images/project-4.png";

import { useState } from "react";

export default function Home() {
  // const [darkMode, setDarkMode] = useState("false");

  return (
    <div /*className={darkMode ? "dark" : ""}*/>
      <Head>
        <title>Skalez Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="gradient-bg-welcome px-5 min-h-screen md:px-20 lg:px-40 dark:bg-white">
        <section className=" min-h-screen">
          <nav className="w-full flex md:justify-center justify-between  ">
            <div className="md:flex-[0.5] flex-initial justify-center items-center	">
              <Image src={logo} alt="logo" className="w-32 cursor-pointer" />
            </div>
            <ul className="flex items-center">
              <li>
                <a
                  className="white-glassmorphism p-3 m-2 cursor-pointer hover:shadow-xl text-white px-4 py-2  rounded-md ml-8"
                  href="#"
                >
                  SkalezDgreat
                </a>
              </li>
              <li>
                <BsFillMoonStarsFill
                  // onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>

          <div className="text-center p-10">
            <h2 className="text-4xl py-2 font-semibold test-gray-200 text-gray-200 md:text-6xl">
              Skalez (Still under construction🏗)
            </h2>
            <h3 className="text-2xl py-5 leading-8 text-gray-200 md:text-3xl">
              {/* {" "} */}
              Web3, Blockchain Developer.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-300 md:text-xl mx-auto max-w-lg ">
              Freelancer providing services for programming, web2 and web3 needs
              in general. Building and learning in the web3 and blockchain in
              general. Looking forward to x1^18.
            </p>
          </div>
          <div className="text-5xl flex justify-center gap-16 py-3 text-gray-300">
            <AiFillGithub />
            <AiFillTwitterCircle />
            <AiFillLinkedin />
          </div>
          <div className="relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 overflow-hidden md:w-92 md:h-92">
            <Image src={profile} layout="fill" objectFit="cover" />
          </div>
        </section>

        <section className="px-10">
          <div>
            <h3 className="text-3xl py-1 text-gray-200">Services I offer</h3>
            <p className="text-md py-2 leading-8 text-gray-300">
              Since the beginning of my journey as a freelance blockchain
              developer, I've done remote jobs for small communities, creating
              smart contracts and partnering with different team members. I've
              worked for <span className="text-teal-500">agencies </span>
              ,consulted for <span className="text-teal-500">startups </span>,
              and collaborated with talented people to create digital products
              for both business and consumer use. I hope to serve you better.
            </p>
            <p className="text-md py-2 leading-8 text-gray-300">
              I offer from a wide range of services, including programming and
              teamwork collaborations.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 mx-auto blue-glassmorphism">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-200">
                Beautiful Designs
              </h3>
              <p className="py-2 text-gray-300">
                Creating elegant designs suited for your needs.
              </p>
              <h4 className="py-4 text-teal-600">Designs tools I use.</h4>
              <p className="text-gray-400 py-1">Remix</p>
              <p className="text-gray-400 py-1">Illustrator</p>
              <p className="text-gray-400 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 blue-glassmorphism">
              <Image
                src={consulting}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-200">
                Beautiful Designs
              </h3>
              <p className="py-2 text-gray-300">
                Creating elegant designs suited for your needs.
              </p>
              <h4 className="py-4 text-teal-600">Designs tools I use.</h4>
              <p className="text-gray-400 py-1">Remix</p>
              <p className="text-gray-400 py-1">Illustrator</p>
              <p className="text-gray-400 py-1">Figma</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 blue-glassmorphism">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2 text-gray-200">
                Beautiful Designs{" "}
              </h3>
              <p className="py-2 text-gray-300">
                Creating elegant designs suited for your needs.
              </p>
              <h4 className="py-4 text-teal-600">Designs tools I use.</h4>
              <p className="text-gray-400 py-1">Remix</p>
              <p className="text-gray-400 py-1">Illustrator</p>
              <p className="text-gray-400 py-1">Figma</p>
            </div>
          </div>
        </section>

        <section>
          <div>
            <h3 className="text-3xl py-1 text-gray-200 ">Portfolio</h3>
            <p className="text-md py-2 leading-8 text-gray-300">
              Since the beginning of my journey as a freelance blockchain
              developer, I've done remote jobs for small communities, creating
              smart contracts and partnering with different team members. I've
              worked for <span className="text-teal-500">agencies </span>
              ,consulted for <span className="text-teal-500">startups </span>,
              and collaborated with talented people to create digital products
              for both business and consumer use. I hope to serve you better.
            </p>
            <p className="text-md py-2 leading-8 text-gray-300">
              I offer from a wide range of services, including programming and
              teamwork collaborations.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={projectOne}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://web3-wallet-sample.vercel.app">
                <Image
                  src={projectTwo}
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={projectThree}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={projectFour}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
